blog/urls.py
from django.conf.urls import url


urlpatterns = [

    # 함수로 구현된 url 목록
    # url(r'^$', 'blog.views.index', name='index'),
    # url(r'^(?P<uuid>[0-9a-f]{32})/$', 'blog.views.detail', name='detail'),
    # url(r'^(?P<pk>\d+)/$', 'blog.views.detail', name='detail'),
    # url(r'^new/$', 'blog.views.new', name='new'),
    # url(r'^(?P<pk>\d+)/edit/$', 'blog.views.edit', name='edit'),

    # Class Based View(클래스)로 구현된 url 목록
    url(r'^$', 'blog.views_cbv.index', name='index'),
    url(r'^(?P<uuid>[0-9a-f]{32})/$', 'blog.views_cbv.detail', name='detail'),
    url(r'^(?P<pk>\d+)/$', 'blog.views_cbv.detail', name='detail'),
    url(r'^new/$', 'blog.views_cbv.new', name='new'),
    url(r'^(?P<pk>\d+)/edit/$', 'blog.views_cbv.edit', name='edit'),



    url(r'^(?P<pk>\d+)/comments/new/$', 'blog.views.comment_new', name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', 'blog.views.comment_edit', name='comment_edit'),

    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', 'blog.views.comment_delete', name='comment_delete'),

    url(r'^image/$', 'blog.views.image', name='image'),
]

pystagram/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from photos import urls as photos_urls
from blog import urls as blog_urls

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^photos/', include(photos_urls)),
    # url(r'^photos/$', 'photos.views.index'),
    # url(r'^photos/(?P<pk>\d+)/$', 'photos.views.detail'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

blog/models.py
import re
from uuid import uuid4
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from pystagram.validators import jpeg_validator
from pystagram.image import receiver_with_image_field
from pystagram.file import random_name_upload_to


def validate_hexstring(value):
    if not re.match(r'^[0-9a-fA-F]+$', value):
        raise ValidationError("hexstring이 아니오.")

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    uuid = models.UUIDField(default=uuid4, editable=False, db_index=True)
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=100, db_index=True) #, validators=[validate_hexstring])
    content = models.TextField()
    photo = models.ImageField(
        blank=True,
        null=True,
        validators=[jpeg_validator],
        upload_to=random_name_upload_to)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked_posts')
    lnglat = models.CharField(max_length=100, blank=True, null=True)
    tags = models.ManyToManyField('Tag', blank=True)
    origin_url = models.URLField(blank=True)
    ip = models.GenericIPAddressField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.pk]) #self.uuid.hex])


receiver = receiver_with_image_field('photo', 1024)
pre_save.connect(receiver, sender=Post)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.name


class Photograph(models.Model):
    #image_url = models.URLField()
    image_file = models.ImageField(upload_to='%Y/%m/%d/')
    description = models.TextField(null=True)
    tags = models.ManyToManyField('Tag')
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from blog.models import Post, Comment
from pystagram.widgets import PointWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ('category', 'title', 'content', 'photo', 'lnglat', 'tags', 'origin_url')
        widgets = {
            'lnglat': PointWidget(attrs={'width':'100%', 'height':'200px'}),
        }

    def clean_title(self):
        title = self.cleaned_data.get('title', '').strip()
        if len(title) < 10:
            raise forms.ValidationError("10자 이상 입력하세요.")
        return title

    def clean(self):
        title = self.cleaned_data.get('title', '')
        content = self.cleaned_data.get('content', '')
        if len(title) < 10 or len(content) <10:
            raise forms.ValidationError("제목과 내용을 필히 !!! 10자 이상 입력하세요.")
        return self.cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseForbidden, Http404
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Category, Comment, Photograph
from blog.forms import PostForm, CommentForm
from .exceptions import HelloWorldError

# from pystagram import settings
from django.conf import settings


# 데코레이터 만들때 가장 기본적인 함수의 유형
# def decorator_name(fn):
#     def wrap(*args, **kwargs):
#         return fn(*args, **kwargs)
#     return wrap

def owner_required(model_cls, field_name='pk'):
    def wrap_outer(view_fn):
        def wrap(request, *args, **kwargs):
            field_value = kwargs[field_name]
            object = get_object_or_404(model_cls, **{field_name: field_value})
            if (not request.user.is_staff) and object.author != request.user:
                return HttpResponseForbidden('invalid user')
            return view_fn(request, *args, **kwargs)

        return wrap

    return wrap_outer


def index(request):
    count = request.session.get('index_page_count', 0) + 1
    request.session['index_page_count'] = count

    post_list = Post.objects.all()

    # messages.debug(request, '메시지 debug')

    lorempixel_categories = (
        "abstract", "animals", "business", "cats", "city", "food", "night",
        "life", "fashion", "people", "nature", "sports", "technics", "transport",
    )

    return render(request, 'blog/index.html', {
        'count': count,
        'post_list': post_list,
        'lorempixel_categories': lorempixel_categories,
    })


def detail(request, pk=None, uuid=None):
    # try:
    #     post = Post.objects.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404

    if pk:
        post = get_object_or_404(Post, pk=pk)
    elif uuid:
        post = get_object_or_404(Post, uuid=uuid)
    else:
        raise Http404

    return render(request, 'blog/detail.html', {
        'post': post,
    })

    '''
    if int(pk) == 0:
        pass
    response = HttpResponse('page not found')
    response['X-Custom-Header'] = 'hello world'
    response.status_code = 404
    response.content_type = 'text/html'
    return response
    '''


@login_required
def new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user

            post.ip = request.META["REMOTE_ADDR"]

            # post.ip = request.META['X_FORWARDED_FOR] # AWS의 로드발란서( Load Balancer ) 사용시

            post.save()
            # post = form.save(commit=False)
            # post.category = get_object_or_404(Category, pk=1)
            # post.save()
            return redirect(post)
            #return redirect('blog:detail', post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/form.html', {
        'form': form,
    })


@login_required
@owner_required(Post, 'pk')
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()

            # 수정 시, author를 지정해 줘야 한다면 아래와 같이 써야함
            # post = form.save(commit=False)
            # post.author = request.user
            # post.save()

            # post = form.save(commit=False)
            # post.category = get_object_or_404(Category, pk=1)
            # post.save()

            return redirect(post)
            #return redirect('blog:detail', post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/form.html', {
        'form': form,
    })


def new_old(request):
    if request.method == "POST":  # "GET", "POST"
        category_id = request.POST["category_id"]
        title = request.POST["title"]
        content = request.POST["content"]

        category = get_object_or_404(Category, pk=category_id)

        post = Post(category=category, title=title, content=content)
        post.save()

        return redirect(post)
        # return redirect('blog:detail', post.pk)

    return render(request, 'blog/form.html', {
    })


@login_required
def comment_new(request, pk):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = get_object_or_404(Post, pk=pk)
            comment.save()
            return redirect(comment.post)
            # return redirect('blog:detail', pk)
    else:
        form = CommentForm()

    return render(request, 'blog/form.html', {
        'form': form,
    })


@login_required
@owner_required(Comment)
def comment_edit(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(comment.post)
            # return redirect('blog:detail', post_pk)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'blog/form.html', {
        'form': form,
    })


@login_required
@owner_required(Comment)
def comment_delete(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        comment.delete()
        messages.success(request, "댓글을 삭제했습니다.")
        return redirect(comment.post)
        # return redirect('blog:detail', post_pk)
    return render(request, 'blog/comment_delete_confirm.html', {
        'comment': comment,
    })


def image(request):
    photo_list = Photograph.objects.all()

    # error 발생
    # raise HelloWorldError('으앙, 에러!')

    return render(request, 'blog/image.html', {
        'photos': photo_list,
    })

blog/templates/blog/comment_delete_confirm.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="alert alert-danger">
                    아래 댓글을 삭제하시겠습니까? 낙장불입!!!
                </div>
                <p>{{ comment.content }}</p>
                <input type="submit" class="btn btn-danger" value="지우겠습니다.">
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ post.title }}
                </div>
                <div class="panel-body">
                    {{ post.content|linebreaks }}

                    {% if post.photo %}
                        <p class="text-center">
                            <img src="{{ post.photo.url }}" alt="">
                        </p>
                    {% endif %}

                    {% if post.lnglat %}
                        <hr>
                        <p class="text-center">
                            <img src="https://maps.googleapis.com/maps/api/staticmap?center={{ post.lat }},{{ post.lng }}&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7Clabel:C%7C{{ post.lat }},{{ post.lng }}" width="300" height="150">
                        </p>
                    {% endif %}

                </div>
            </div>

            <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.content }}
                        <a href="{% url "blog:comment_edit" post.pk comment.pk %}">Edit</a>
                        <a href="{% url "blog:comment_delete" post.pk comment.pk %}">Delete</a>
                    </li>
                {% endfor %}
            </ul>

            <a href="{% url "blog:index" %}" class="btn btn-default">글목록</a>
            <a href="{% url "blog:edit" post.pk %}" class="btn btn-info">수정</a>
            <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-success">새 댓글</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/error.html
<h1>{{error}}</h1>

<p>{{status}}</p>

blog/templates/blog/form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary" value="글쓰기">
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/image.html
{% extends 'layout.html' %}

{% block title %}사진들{% endblock %}

{% block content %}

    {% if request.last_post %}
        <p>
            마지막 사진 PK : {{ request.last_post.pk }}
        </p>

    {% else %}

    <p>마지막 사진이 없음요.</p>

    {% endif %}

    <p>사진들</p>
    {% for photo in photos %}
    <p><img src="{{photo.image_file.url}}" /></p>
    {% endfor %}

{% endblock %}

blog/templates/blog/index.html
{% extends "blog/layout.html" %}
{% load bootstrap3 thumbnail %}
{% load my_tags %}

{% block extra_head %}
<!-- 참고 : http://tobyyun.tumblr.com/post/55858430437/css%EB%A5%BC-%ED%86%B5%ED%95%9C-%EB%A9%80%ED%8B%B0%EB%9D%BC%EC%9D%B8-%EB%A7%90%EC%A4%84%EC%9E%84-%EC%B2%98%EB%A6%AC%EC%99%80-%ED%8F%B4%EB%B0%B1 -->
<style>
.thumbnail .caption h5 {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
    word-wrap: break-wrap;
}
.thumbnail .caption {
    height: 50px;
}
</style>

<title>Pystagram</title>
{% endblock %}

{% block navbar_left %}
    <li><a><span class="label label-info">{{ count }}</span></a></li>
{% endblock %}

{% block content %}

<div>
    <p>
        {% url "blog.views.detail" post.pk as post_url %}

        GA 붙인 URL : {{post_url|ga_url:"source=facebook&medium=personalpage&campaign=python"}}
    </p>
</div>

<div class="container">
    <div class="row">
        {% for post in post_list %}
            <div class="col-xs-6 col-sm-4 col-md-3">
                <div class="thumbnail">
                    <a href='{% url "blog:detail" post.pk %}'>

                        {% if not post.photo %}
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="400" height="400" class="img-rounded" />
                        {% else %}
                            {% thumbnail post.photo "400x400" crop="center" as im %}
                                <img src="{{ im.url }}" width="400" height="400" class="img-rounded" />
                            {% endthumbnail %}
                        {% endif %}

                        <!--{% if post.photo %}-->
                            <!--&lt;!&ndash;<img src="{{ post.photo.url }}" class="img-rounded">&ndash;&gt;-->
                            <!--{% thumbnail post.photo "400x400" crop="center" as im %}-->
                                <!--<img src="{{ im.url }}" width="400" height="400" class="img-rounded">-->
                            <!--{% endthumbnail %}-->
                            <!--{% thumbnail post.photo "800x800" crop="center" as im %}-->
                                <!--<img src="{{ im.url }}" width="400" height="400" class="img-rounded">-->
                            <!--{% endthumbnail %}-->
                        <!--{% endif %}-->

                        <!--<img src="http://lorempixel.com/400/400/{{ lorempixel_categories|random }}/" class="img-rounded" />-->
                        <div class="caption">
                            <h5>{{ post.title }}</h5>
                        </div>
                    </a>
                    <a href='{% url "blog:detail" post.uuid.hex %}'>by uuid</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row text-center">
        {% bootstrap_pagination page_obj %}
    </div>
</div>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}